package-lock.json, package.json
Bumping dicomweb-client version to 0.4.2
=> bupping dicomweb-client version to 0.4.2

.gitignore, src/api.js, src/dicom-microscopy-viewer.js, src/roi.js, src/scoord3d.js, test/api.spec.js
Refactoring the SCOORD3D following @hackermd suggestions at the PR https://github.com/dcmjs-org/dicom-microscopy-viewer/pull/8.
=> Migrating to scoord3d

examples/basic/index.html, examples/events/index.html, src/api.js
HTML and javascript changes in order to support a good mobile experience
The demos should be human usable for mobile users :)
=> Mobile layout

examples/basic/index.html, examples/events/index.html, examples/simple_viewer/index.html, src/api.js
Hardcodes the transfer syntax if we are not using retrieveRendered
=> fix(transfer-syntax): Hardcode transferSyntaxUID for retrieveInstanceFrame requests

src/viewer.js
Add new function that allows application to add components to render overlay information.
=> Add new function to add map overlays

src/scoord3dUtils.js
=> Issue 51: Fix measurement calculation

src/metadata.js
Fix for grouping colored images. Find out while applying last review in https://github.com/MGHComputationalPathology/slim/pull/25
=> fix RGB images grouping function

package-lock.json, package.json, src/metadata.js
As per discussion in https://github.com/MGHComputationalPathology/slim/issues/40#issuecomment-885608382, updating OpenLayer version. Tested over https://github.com/MGHComputationalPathology/slim/pull/25
=> Update OpenLayer to version 6.6.1

src/annotations/markups/measurement.js, src/scoord3dUtils.js, src/viewer.js
- After scoord3dUtils changes to throw new exceptions we need to properly handle them.
=> Handle area and length calc exceptions

src/viewer.js
Addresses https://github.com/MGHComputationalPathology/slim/issues/55
=> Disable zoom on overview map

src/channel.js
fix https://github.com/MGHComputationalPathology/slim/issues/39 @hackermd , see video https://www.dropbox.com/s/haugu2uoifea9ol/2022-02-07%2014-44-26.mp4?dl=0
=> Re slim issue 39: fix shift on zoom

src/pyramid.js, src/utils.js
This PR fixes the issue [#84](https://github.com/ImagingDataCommons/idc-slim/issues/84) related to open a monocromatic multichannel image
=> Fix/idc slim issue#84

package-lock.json, package.json
Update the versions.  Also want to commit it with a fix message to force  build/release cycle.
=> fix(version): Update package versions to newer releases.

.github/workflows/publish.yml
=> Add npm publish workflow

src/viewer.js
=> Add missing move events

package.json
This change is necessary because there is no `./config/webpack` file.
=> fix: webpack script

src/bulkAnnotations/utils.js
getFeaturesFromBulkAnnotations(...) previously called getAffineBasedOnPyramidLevel(...) per feature.
=> perf(bulkAnnotations): cache affine

src/bulkAnnotations/utils.js
isCoordinateInsideBoundingBox did not work for negative coordinates. now fixed, plus simplified.
=> fix(critical): isCoordinateInsideBoundingBox 

package.json
- https://github.com/ImagingDataCommons/dicom-microscopy-viewer/pull/159
- https://github.com/ImagingDataCommons/dicom-microscopy-viewer/pull/158
- https://github.com/ImagingDataCommons/dicom-microscopy-viewer/pull/156
- https://github.com/ImagingDataCommons/dicom-microscopy-viewer/pull/155
- https://github.com/ImagingDataCommons/dicom-microscopy-viewer/pull/154
=> Bump version to 0.47.2

package.json
=> feat: bump to 0.47.3

src/roi.js, src/viewer.js
- Address thumbnail rendering issue
- Refactor event handlers
=> fix: overview thumbnails

package.json
=> Bump version to 0.48.0

.gitignore, src/viewer.js
- Add a new option to disable interactions for the overview and non volume viewports
=> Add disable interactions options to non volume viewports

.github/workflows/unit-tests.yml, config/webpack/webpack-dynamic-import.js
- Update dynamic import config to use window
=> feat: Use window for dynamic import

package.json
=> Bump version to 0.48.1

package.json
- Bump version to cut new release
=> Update version to 0.48.7

src/viewer.js
- Avoid runtime errors using get func
=> fix: Add check to roi func

src/viewer.js
https://github.com/ImagingDataCommons/slim/issues/321
- Display range information
- Rendering correction
=> fix: Issues displaying parametric maps

src/viewer.js
- Add method to toggle segment interpolation
=> feat: Add segment interpolation toggle

package.json
=> Bump version to 0.48.8

package.json, src/viewer.js
- https://github.com/ImagingDataCommons/slim/issues/333
- https://github.com/ImagingDataCommons/slim/issues/332
- https://github.com/ImagingDataCommons/slim/issues/331
- https://github.com/ImagingDataCommons/slim/issues/330
=> fix: Address regressions introduced by recent new features & refactoring
