src/api.js

key down event listener was removed
Currently, when users start drawing and press escape it generates an error as the issue https://github.com/dcmjs-org/dicom-microscopy-viewer/issues/16

removing keydown event listener

---

src/api.js
src/dicom-microscopy-viewer.js
src/metadata.js
src/roi.js
src/scoord3d.js
src/utils.js
test/api.spec.js

This PR adds a `uid` property to `ROI` objects, which will facilitate tracking of regions and measurement groups.

Add UID to ROI objects

---

src/api.js

a new function to update the size of the canvas
There is an open issue at Viewers https://github.com/OHIF/Viewers/issues/550 which says that Viewport is resizing incorrectly when the sidebars are changed. It appears to be resizing in CSS but not calling a redraw of the rendering on the Canvas. Note how the actual cell aspect ratios are being changed. This is not what should be happening.

adding updateSize function

---

package-lock.json
package.json
src/api.js

Addresses #32.
**Note:** This depends on https://github.com/dcmjs-org/dicomweb-client/pull/16, so we shouldn't merge this until that PR is merged and we can depend on an updated version of dicomweb-client. For that reason, this is marked as a Draft PR.
This is a bit of deja vu from this issue (https://github.com/dcmjs-org/dicom-microscopy-viewer/pull/23).
This just switches from the hardcoded mimetype string to a hardcoded mediatypes array. Nothing changes to the end user, but it will fix the quotation mark issue we have that is breaking usage of this library with Google Cloud Healthcare (#32).

fix(api.js): Update DICOMWebClient usage to use mediatypes array format

---

src/metadata.js

'rows': TileHeight (tag: (0x0028, 0x0010))
'columns': TileWidth (tag: (0x0028, 0x0011))
'ColumnPositionInTotalImagePixelMatrix' (tag: (0x0048, 0x021E))
'RowPositionInTotalImagePixelMatrix' (tag: (0x0048, 0x021F))
rowIndex, colIndex should be
rowIndex = Math.ceil(RowPositionInTotalImagePixelMatrix / TileHeight);
colIndex = Math.ceil(ColumnPositionInTotalImagePixelMatrix / TileWidth);
If this problem doesn't be fixed, it would fail while TileHeigh != TileWidth

fix: rowIndex, colIndex calculations in getFrameMapping()

---

package-lock.json
package.json
src/viewer.js

This PR includes the following changes:
- Make overviews collapsible (see https://github.com/herrmannlab/slim/issues/91)
- Provide option to enable/disable preloading of tiles for next higher resolution level (disabled by default)
- Fix listener for annotation group loading errors

Improve configuration 

---

CONTRIBUTING.md
README.md
package.json
src/annotations/markups/_MarkupManager.js
src/annotations/markups/measurement.js
src/enums.js
src/viewer.js

- When drawing measurements the first click was dragging the viewport instead of starting the drawing 
- When modifying the geometry the label and linked line was not having its coordinates updated (moving the label the annotation was anchored to the old geometry shape before it was modified)
- Addressed console errors caused by accessing optional values
- Update unit from array to codedConcept to avoid dcmjs errors

Address annotation issues

---

jest.config.js
src/viewer.js

This change was created on a client request to enable the viewer to show the entire image when is displaying on small screens. Without this change, the Zoom doesn't allow the user to completely out of the image.
With this change allowed, this will be the behavior:
Without this change, this is the actually behavior:

Added new property to allow change default resolutions

---

README.md
config/webpack/webpack-dynamic-import.js
package-lock.json
package.json
src/viewer.js

The default setup for dynamic import was such that the libraries would overlap with other libraries having the same names, which caused version mismatches when using the dynamic import version.  This change makes the path separate.  As well, it allows a named load for the library, which means the library can actually be used natively in the browser again, fixing issues with deployment standalone.

fix: Setup the dynamic import so it is separate from other packages

---

src/viewer.js

- Avoid double click event with draw interaction active to avoid conflicts with the draw events

fix(viewer.js): Avoid double click for draw interaction

---

.github/workflows/publish.yml

for the reference see https://docs.npmjs.com/generating-provenance-statements#publishing-packages-with-provenance-via-github-actions

add permissions to publish npm packages with provenance

---

src/events.js
src/viewer.js

Adding pointer move event to enable detecting hovering over features.

feat: add pointer move event

---

package.json
src/annotation.js
src/utils.js
src/viewer.js

Addresses: https://github.com/ImagingDataCommons/slim/issues/235

feat: monitor bulk ann downloads

---

src/viewer.js

Addresses: https://github.com/ImagingDataCommons/slim/issues/245
Removes the background color of the segmentations. Use the following dataset to test with slim:
`https://healthcare.googleapis.com/v1/projects/idc-sandbox-000/locations/us-central1/datasets/fedorov-dev-healthcare/dicomStores/singlebitsegstest/dicomWeb`

fix: remove segmentation background

---

babel.config.js

-Request: Target IE 11 #35
Updates the Babel configuration to align with other dcmjs-org libraries by providing an IE 11 compatible build out of the box. This change will make the package easier to use as a dependency since consumers targeting IE 11 won't need to transpile this dependency on every build.
- Removed `node: 'current'` target as it's not necessary (Jest tests work fine without it)
- Removed redundant `@babel/plugin-proposal-object-rest-spread` plugin since it's included in `@babel/preset-env` by default
- Simplified configuration to target IE 11 browsers, matching the approach used in other dcmjs-org repositories
- This configuration ensures compatibility with IE 11 while maintaining support for all modern browsers
- The simplified configuration follows the pattern …

Add ie support

---

src/viewer.js

Fixing fractional segmentations:
1 - fixing color palette and maintaining transparent background
2 - removing color palette overlay for binary segmentations
3 - removing annoying zoom when activating segmentations
Addresses: https://github.com/ImagingDataCommons/slim/issues/245
Binary segmentation now = no background and no color palette overlay:
Fractional segmentation now = no background and proper colors:

fix: fractional segmentation

---

src/viewer.js

Fixes: https://github.com/ImagingDataCommons/slim/issues/287
As discussed in the ticket above, now we'll only have a single overlay, no matter how many fractional segments are active. Whenever we delete or hide all fractional segments, then the overlay disappears. And it only shows again when any of the segments is activated.

feat: use single fractional segment colorbar

---

src/eventPublisher.js
src/events.js
src/viewer.js

This PR introduces:
* an event that is published when the viewport is clicked, allowing consumers to:
* Update their selected features properties.
* Execute callbacks appropriately.
* a clear selections method to:
* allow consumers to programatically clear selections instead of relying on user clicks 
This change is necessary for: [slim#196](https://github.com/ImagingDataCommons/slim/issues/196)
* Graceful Handling of Missing ROIs
When attempting to retrieve a ROI that isn't found, it now logs a warning instead of throwing an error or displaying one to the user.
* Safe Access to `el` in the `publish` function
Added optional chaining to handle cases where the `el` variable may be undefined in the published event payload.

feat: add viewport clicked event and clear selections method

---

config/webpack/webpack-dynamic-import.js

- Use dmv sub directory for wasm files to avoid import conflicts
- Relative for js files

fix: use dmv folder for wasm files

---

src/viewer.js

There is a hard-coded filter on the "ContentLabel" of a parametric map, such that it will not display unless the ContentLabel is exactly "HEATMAP".
This PR simply removes this limitation such that a parametric map should display regardless of its ContentLabel

Remove content label filter for parametric maps

---

package.json
src/pyramid.js
src/viewer.js
yarn.lock

Turned off interpolated values when resampling. By default, the nearest neighbor is used when resampling.
- https://github.com/ImagingDataCommons/slim/issues/317
Before:
After:

fix: Turn off interpolation for special unmatched resolution seg case
